Make docker run on linux, disable tendermint on osx

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -17,6 +17,7 @@ addons:
   chrome: stable
 
 before_install:
+- export TM_VERSION=0.20.0
 # yarn is outdated on Linux images
 - |
   if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
@@ -26,29 +27,34 @@ before_install:
     sudo apt-get install -y libudev-dev libusb-1.0-0 libusb-1.0-0-dev
     npm install -g node-gyp
   fi
-- export TM_VERSION=0.20.0
-- docker pull tendermint/tendermint:${TM_VERSION}
+# detect whether we can use docker, but don't fail if impossible
+# this currently passes on linux, fails on osx
+- (docker pull tendermint/tendermint:${TM_VERSION} && export TENDERMINT_ENABLED=1) || true
 
 install:
 - yarn install
 
 before_script:
-- ./packages/tendermint-rpc/tendermint.sh > /tmp/foo.log &
-- export TM_PID=$!
-- echo "Started tendermint" $TM_PID
-- export TENDERMINT_ENABLED=1
-- sleep 2
-# for debug output
-- cat /tmp/foo.log
+- |
+  if [[ $TENDERMINT_ENABLED ]]; then
+    ./packages/tendermint-rpc/tendermint.sh > /tmp/foo.log &
+    export TM_PID=$!
+    echo "Started tendermint" $TM_PID
+    sleep 2
+    # for debug output
+    cat /tmp/foo.log
+  fi
 
 script:
 - echo "use tendermint?" ${TENDERMINT_ENABLED}
 - ./travis.sh
 
 after_script:
-- echo "Stopping tendermint" $TM_PID
-- kill ${TM_PID}
-# - cat /tmp/foo.log
+- |
+  if [[ $TM_PID ]]; then
+    echo "Stopping tendermint" $TM_PID
+    kill ${TM_PID}
+  fi
 
 # whitelist long living branches to avoid testing feature branches twice (as branch and as pull request)
 branches:
